### PR TITLE
WS

### LINKED ISSUE #4: WebSockets
Ws ("path/of/channel")

### PR DESCRIPTION
**Pull request by kelyar**
Could you please take a look? Should close #4

### CODE REVIEW

**Comment by grsmv** [comment]
Wow. This is amazing. Great thanks! 
I want to do some tests before merge - websocket channels should have completely separate IO.

**Comment by grsmv** [comment]
Evgeniy, please tell me on which version of Go you tested this solution? Also some information about your environment would be helpful. I have some troubles with new code - channels is already closed all the time. Right after creation.
As I see now - it's not a problem with realisation, it's a problem with env, 'cause some other WebSocket examples (1) are not usable on latest Go build.

1 - https://raw.github.com/ukai/go-websocket-sample/master/websocket_echo_sample.go

**Comment by grsmv** [comment]
Actually, here's code of an sample application, on which I made all tests: https://gist.github.com/grsmv/7553835
Chrome and Safari complaining about closed connections.

**Comment by kelyar** [comment]
That's interesting. I use "go version go1.1.2 linux/386". Will try to run your gist today.

**Comment by grsmv** [comment]
Really sorry for rejecting your code, but I just can't get it work properly. WebSockets already appear with closing issue #4

**Comment by kelyar** [comment]
It's ok) It still didn't meet all your requirements

**Pull request closed without merging**
