### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kelyar**
I removed mentioning of carcass and fixed some typos. Do you think it still can be called DSL? It looks more like solid framework for me :)

### CODE REVIEW

**Comment by grsmv** [comment]
Thank you very much! =) 

Actually, I like introduction from http://cliohq.github.io/clio much more:

"Clio is a small and compact framework, which will allow you to start writing big web-applications with minimal effort right now. Simple and convenient, it includes routing, template system, asset management, generators and multiple useful tools, which will make your development process fast and effective.

We believe that you smart enough to choose your own way of organizing your application as wel as database layer, that completelly fits your needs. Therefore Clio just gives you bunch of tools, that you can use however you want."

**Comment by kelyar** [comment]
you're right, it's much better) ready for demo tomorrow? :)

**Comment by grsmv** [comment]
"I was born ready" haha :)

**Comment by kelyar** [comment]
btw is it old file structure on screenshot? app/src? completion?

**Pull request merged**
