### PR TITLE
small fixes + manage-assets from public

### PR DESCRIPTION
**Pull request by kelyar**

### CODE REVIEW

**Comment by grsmv** [comment]
Wow! Thanks for fixes and assets management. Please note, that assets management model can be changed in a future and, in common, framework is "in progress" mode.

Thanks a lot again :)

PS. Also hope to see you on Script'n'Code event, dedicated to Go programming language at he end of September (https://www.facebook.com/ScriptAndCode)

Cheers :)

**Comment by kelyar** [comment]
Sure, right assets management is hard to implement. Just something simple to start with.

I hope to be there but I have tickets to Rubyshift, so depends on date)

**Comment by grsmv** [comment]
Sorry - at the end of October - we have a gap in September. 
Spoilers: Andrew Gerrand, Go core team member, will be first presenter :)

**Comment by kelyar** [comment]
Sounds great, I am in)

**Pull request merged**
